apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-server-debug
  labels:
    app: ml-server 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-server
  template:
    metadata:
      labels:
        app: ml-server
    spec:
      containers:
        - name: ml-server
          image: 679oose/ml-server:debug
          ports:
            - containerPort: 80
          env:
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: mysql-url

          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-user

          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-password

---
apiVersion: v1
kind: Service
metadata:
  name: ml-server-service
spec:
  type: NodePort
  selector:
    app: ml-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 30001

        



    